name = input("Введите Ваше имя ")
address = input("Введите Ваш адрес проживания в формате: город, область, почтовый индекс ")
phone = input("Введите Ваш номер телефона ")
specialization = input("Введите Вашу специализация в учебном заведении ")
print("Имя:", name)
print("Адрес проживания:", address)
print("Номер телефона:", phone)
print("Специализация:", specialization)
