import turtle
turtle.screensize(500,500)
turtle.speed(1)
turtle.begin_fill()
turtle.fillcolor("grey")
turtle.right(45)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()
turtle.begin_fill()
turtle.fillcolor("grey")
turtle.left(-90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.right(-90)
turtle.forward(100)
turtle.right(-90)
turtle.forward(100)
turtle.end_fill()
turtle.clear()



