import turtle
turtle.goto(0,0)
turtle.hideturtle()
turtle.penup()
turtle.forward(50)
turtle.left(90)
turtle.pendown()
turtle.showturtle()
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.hideturtle()
turtle.begin_fill()
turtle.fillcolor("red")
turtle.circle(50) #круг радиусом 80 нельзя вписать в квадрат со стороной 100, т.к. диаметр круга=160
turtle.end_fill()
turtle.done